version: 2

sources:
  - name: tpch_sample
    database: DBT_RAW
    schema: TPCH_SF{{ var('tpch_size', 1) }}
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION
